// <auto-generated />
using System;
using JobPosting.Api.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JobPosting.Api.Persistence.Migrations
{
    [DbContext(typeof(PostingDbContext))]
    [Migration("20261005172328_InitialPosting")]
    partial class InitialPosting
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JobPosting.Api.Persistence.IdempotencyRecord", b =>
                {
                    b.Property<string>("Scope")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("scope");

                    b.Property<string>("KeyDigest")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key_digest");

                    b.Property<int>("CanonicalizationVersion")
                        .HasColumnType("integer")
                        .HasColumnName("canonicalization_version");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("fingerprint");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<string>("ResponseJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("response_json");

                    b.HasKey("Scope", "KeyDigest");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.HasIndex("JobId")
                        .IsUnique();

                    b.HasIndex("EventId", "JobId");

                    b.ToTable("idempotency_records", null, t =>
                        {
                            t.HasCheckConstraint("ck_ledger_identity", "scope = 'create-job' AND key_digest ~ '^[a-f0-9]{64}$' AND fingerprint ~ '^[a-f0-9]{64}$' AND canonicalization_version > 0 AND isfinite(created_at)");

                            t.HasCheckConstraint("ck_ledger_response", "(octet_length(response_json) <= 131072 AND json_typeof(response_json::json) = 'object' AND response_json::json->>'id' = job_id::text AND response_json::json->>'status' = 'accepted') IS TRUE");
                        });
                });

            modelBuilder.Entity("JobPosting.Api.Persistence.JobPostingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("ClosingDate")
                        .HasColumnType("date")
                        .HasColumnName("closing_date");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("department");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("location");

                    b.Property<decimal>("SalaryMax")
                        .HasColumnType("numeric")
                        .HasColumnName("salary_max");

                    b.Property<decimal>("SalaryMin")
                        .HasColumnType("numeric")
                        .HasColumnName("salary_min");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("jobs", null, t =>
                        {
                            t.HasCheckConstraint("ck_jobs_created", "isfinite(created_at)");

                            t.HasCheckConstraint("ck_jobs_date", "closing_date BETWEEN DATE '0001-01-01' AND DATE '9999-12-31'");

                            t.HasCheckConstraint("ck_jobs_identity", "id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_jobs_salary", "salary_min >= 0 AND salary_max <= 999999999.99 AND salary_min < salary_max AND scale(salary_min) <= 2 AND scale(salary_max) <= 2");

                            t.HasCheckConstraint("ck_jobs_text", "title ~ '[^[:space:]]' AND department ~ '[^[:space:]]' AND location ~ '[^[:space:]]' AND description ~ '[^[:space:]]' AND char_length(description) <= 10000");
                        });
                });

            modelBuilder.Entity("JobPosting.Api.Persistence.OutboxMessage", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<long>("ClaimGeneration")
                        .HasColumnType("bigint")
                        .HasColumnName("claim_generation");

                    b.Property<string>("EnvelopeJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("envelope_json");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<DateTimeOffset?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_expires_at");

                    b.Property<Guid?>("LeaseOwner")
                        .HasColumnType("uuid")
                        .HasColumnName("lease_owner");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("EventId");

                    b.HasIndex("JobId")
                        .IsUnique();

                    b.HasIndex("NextAttemptAt", "LeaseExpiresAt")
                        .HasDatabaseName("ix_outbox_due_pending")
                        .HasFilter("published_at IS NULL");

                    b.ToTable("outbox_messages", null, t =>
                        {
                            t.HasCheckConstraint("ck_outbox_envelope", "(octet_length(envelope_json) <= 131072 AND json_typeof(envelope_json::json) = 'object' AND envelope_json::json->>'eventId' = event_id::text AND envelope_json::json->>'eventType' = event_type AND (envelope_json::json->>'schemaVersion')::integer = schema_version AND envelope_json::json->'job'->>'id' = job_id::text) IS TRUE");

                            t.HasCheckConstraint("ck_outbox_identity", "event_id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_outbox_progress", "attempt_count >= 0 AND claim_generation >= 0 AND (lease_owner IS NULL) = (lease_expires_at IS NULL) AND (published_at IS NULL OR lease_owner IS NULL)");

                            t.HasCheckConstraint("ck_outbox_schema", "event_type = 'JobPostingCreated' AND schema_version > 0");

                            t.HasCheckConstraint("ck_outbox_times", "isfinite(occurred_at) AND isfinite(next_attempt_at) AND (lease_expires_at IS NULL OR isfinite(lease_expires_at)) AND (published_at IS NULL OR isfinite(published_at))");
                        });
                });

            modelBuilder.Entity("JobPosting.Api.Persistence.IdempotencyRecord", b =>
                {
                    b.HasOne("JobPosting.Api.Persistence.JobPostingEntity", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JobPosting.Api.Persistence.OutboxMessage", null)
                        .WithMany()
                        .HasForeignKey("EventId", "JobId")
                        .HasPrincipalKey("EventId", "JobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("JobPosting.Api.Persistence.OutboxMessage", b =>
                {
                    b.HasOne("JobPosting.Api.Persistence.JobPostingEntity", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
