// <auto-generated />
using System;
using JobSearch.Api.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JobSearch.Api.Persistence.Migrations
{
    [DbContext(typeof(SearchDbContext))]
    partial class SearchDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("job_ingestion_sequence");

            modelBuilder.Entity("JobSearch.Api.Persistence.SearchJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("ClosingDate")
                        .HasColumnType("date")
                        .HasColumnName("closing_date");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("department");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("description");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<int>("HashVersion")
                        .HasColumnType("integer")
                        .HasColumnName("hash_version");

                    b.Property<long>("IngestionSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("ingestion_sequence");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("location");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("payload_hash");

                    b.Property<decimal>("SalaryMax")
                        .HasColumnType("numeric")
                        .HasColumnName("salary_max");

                    b.Property<decimal>("SalaryMin")
                        .HasColumnType("numeric")
                        .HasColumnName("salary_min");

                    b.Property<long>("SourceCreatedAtTicks")
                        .HasColumnType("bigint")
                        .HasColumnName("source_created_at_ticks");

                    b.Property<long>("SourceOccurredAtTicks")
                        .HasColumnType("bigint")
                        .HasColumnName("source_occurred_at_ticks");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_jobs");

                    b.HasIndex("Department")
                        .HasDatabaseName("ix_jobs_department_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Department"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Department"), new[] { "gin_trgm_ops" });

                    b.HasIndex("Description")
                        .HasDatabaseName("ix_jobs_description_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Description"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Description"), new[] { "gin_trgm_ops" });

                    b.HasIndex("EventId")
                        .IsUnique()
                        .HasDatabaseName("ux_jobs_event_id");

                    b.HasIndex("IngestionSequence")
                        .IsUnique()
                        .HasDatabaseName("ux_jobs_ingestion_sequence");

                    b.HasIndex("Location")
                        .HasDatabaseName("ix_jobs_location_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Location"), new[] { "gin_trgm_ops" });

                    b.HasIndex("Title")
                        .HasDatabaseName("ix_jobs_title_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Title"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Title"), new[] { "gin_trgm_ops" });

                    b.HasIndex("CreatedAt", "Id")
                        .IsDescending()
                        .HasDatabaseName("ix_jobs_newest");

                    b.HasIndex("ClosingDate", "CreatedAt", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("ix_jobs_closing");

                    b.ToTable("jobs", null, t =>
                        {
                            t.HasCheckConstraint("ck_jobs_date", "closing_date BETWEEN DATE '0001-01-01' AND DATE '9999-12-31'");

                            t.HasCheckConstraint("ck_jobs_hash", "payload_hash ~ '^[a-f0-9]{64}$' AND hash_version = 1");

                            t.HasCheckConstraint("ck_jobs_identity", "id <> '00000000-0000-0000-0000-000000000000'::uuid AND event_id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_jobs_salary", "salary_min >= 0 AND salary_max <= 999999999.99 AND salary_min < salary_max AND scale(salary_min) <= 2 AND scale(salary_max) <= 2");

                            t.HasCheckConstraint("ck_jobs_sequence", "ingestion_sequence > 0");

                            t.HasCheckConstraint("ck_jobs_text", "length(btrim(title)) > 0 AND length(btrim(department)) > 0 AND length(btrim(location)) > 0 AND length(btrim(description)) > 0");

                            t.HasCheckConstraint("ck_jobs_ticks", "source_created_at_ticks BETWEEN 0 AND 3155378975999999999 AND source_occurred_at_ticks BETWEEN 0 AND 3155378975999999999");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
